// Seed Board definitions. A Board represents a famous company, brand, category,
// community, topic, movement, or cultural entity that users compete to rule.
//
// Each definition is static identity data. Live competitive state (crown holder,
// value, viewers, momentum, history) is built on top of these in state.js.

export const BOARD_DEFS = [
  {
    slug: 'apple',
    name: 'Apple',
    category: 'Technology',
    entity: 'Company',
    accent: '#e6e6eb',
    glow: '#bfc4cc',
    tagline: 'The most valuable crown in the arena.',
  },
  {
    slug: 'tesla',
    name: 'Tesla',
    category: 'Automotive · Energy',
    entity: 'Company',
    accent: '#ff4d4d',
    glow: '#ff2d2d',
    tagline: 'High volatility. High reward.',
  },
  {
    slug: 'bitcoin',
    name: 'Bitcoin',
    category: 'Crypto',
    entity: 'Movement',
    accent: '#f7931a',
    glow: '#f7931a',
    tagline: 'The crown that never sleeps.',
  },
  {
    slug: 'openai',
    name: 'OpenAI',
    category: 'Artificial Intelligence',
    entity: 'Company',
    accent: '#10a37f',
    glow: '#19c39a',
    tagline: 'Where the agents feel at home.',
  },
  {
    slug: 'nike',
    name: 'Nike',
    category: 'Apparel · Sport',
    entity: 'Brand',
    accent: '#cfff04',
    glow: '#aef000',
    tagline: 'Just claim it.',
  },
  {
    slug: 'netflix',
    name: 'Netflix',
    category: 'Streaming · Media',
    entity: 'Company',
    accent: '#e50914',
    glow: '#ff0a16',
    tagline: 'Binge the throne.',
  },
  {
    slug: 'coca-cola',
    name: 'Coca-Cola',
    category: 'Beverages',
    entity: 'Brand',
    accent: '#f40009',
    glow: '#ff1f27',
    tagline: 'A century of attention.',
  },
  {
    slug: 'disney',
    name: 'Disney',
    category: 'Entertainment',
    entity: 'Company',
    accent: '#3aa0ff',
    glow: '#4db5ff',
    tagline: 'The kingdom of legacy.',
  },
  {
    slug: 'spacex',
    name: 'SpaceX',
    category: 'Aerospace',
    entity: 'Company',
    accent: '#9b8cff',
    glow: '#b0a3ff',
    tagline: 'Reach escape velocity.',
  },
  {
    slug: 'nvidia',
    name: 'Nvidia',
    category: 'Semiconductors · AI',
    entity: 'Company',
    accent: '#76b900',
    glow: '#8fe000',
    tagline: 'The accelerated crown.',
  },
  {
    slug: 'ethereum',
    name: 'Ethereum',
    category: 'Crypto',
    entity: 'Movement',
    accent: '#8a92f0',
    glow: '#a6acff',
    tagline: 'Programmable legacy.',
  },
  {
    slug: 'spotify',
    name: 'Spotify',
    category: 'Audio · Streaming',
    entity: 'Brand',
    accent: '#1db954',
    glow: '#23e066',
    tagline: 'Set the arena soundtrack.',
  },
];

export const BOARD_SLUGS = BOARD_DEFS.map((b) => b.slug);
